# Generated by Django 6.0.6 on 2026-06-14 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng', models.CharField(max_length=100)),
                ('tr', models.CharField(max_length=100)),
                ('example', models.TextField()),
                ('liste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kelimeler.list')),
            ],
        ),
    ]
