# Generated by Django 6.0.6 on 2026-06-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelimeler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='is_learned',
            field=models.BooleanField(default=False),
        ),
    ]
